fixup! fixup! HOTFIX Build vodozemac web

diff --git a/.github/workflows/image.yaml b/.github/workflows/image.yaml
--- a/.github/workflows/image.yaml
+++ b/.github/workflows/image.yaml
@@ -53,8 +53,11 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Clean git working directory
-        run: git clean -fdx
+        run: git clean -fdx || echo "Warning: git clean failed, but continuing with the build process..."
 
       - name: Build and push image
         uses: docker/build-push-action@v6
@@ -113,8 +116,11 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        
       - name: Clean git working directory
-        run: git clean -fdx
+        run: git clean -fdx || echo "Warning: git clean failed, but continuing with the build process..."
 
       - name: Build and push image
         uses: docker/build-push-action@v6
