fixup! fixup! HOTFIX Build vodozemac web

diff --git a/.github/workflows/image.yaml b/.github/workflows/image.yaml
--- a/.github/workflows/image.yaml
+++ b/.github/workflows/image.yaml
@@ -57,7 +57,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Clean git working directory
-        run: git clean -fdx || echo "Warning: git clean failed, but continuing with the build process..."
+        run: git clean -fdx || echo "Warning git clean failed, but continuing with the build process..."
 
       - name: Build and push image
         uses: docker/build-push-action@v6
@@ -120,7 +120,7 @@ jobs:
         uses: actions/checkout@v4
       
       - name: Clean git working directory
-        run: git clean -fdx || echo "Warning: git clean failed, but continuing with the build process..."
+        run: git clean -fdx || echo "Warning git clean failed, but continuing with the build process..."
 
       - name: Build and push image
         uses: docker/build-push-action@v6
